// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeekendFlights.Infrastructure.Persistence;

#nullable disable

namespace WeekendFlights.Infrastructure.Migrations
{
    [DbContext(typeof(WeekendFlightsDbContext))]
    [Migration("20260708043811_AddFlightSearchIndexes")]
    partial class AddFlightSearchIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeekendFlights.Domain.Entities.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("CityKiwiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DestinationPopularityScore")
                        .HasColumnType("double precision");

                    b.Property<int>("GlobalRankDestination")
                        .HasColumnType("integer");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("IcaoCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("KiwiId")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Rank")
                        .HasColumnType("numeric");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("idx_airport_city");

                    b.HasIndex("IataCode")
                        .IsUnique()
                        .HasDatabaseName("idx_airport_iata");

                    b.HasIndex("KiwiId")
                        .IsUnique()
                        .HasDatabaseName("idx_airport_kiwi_id");

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("WeekendFlights.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("KiwiId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("idx_city_code");

                    b.HasIndex("KiwiId")
                        .IsUnique()
                        .HasDatabaseName("idx_city_kiwi_id");

                    b.HasIndex("Name", "Country")
                        .HasDatabaseName("idx_city_name_country");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("WeekendFlights.Domain.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailabilitySeats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("BookingToken")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CityCodeFrom")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CityCodeTo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CityFrom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CityTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CountryFrom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CountryTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DeepLink")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<decimal>("DurationDeparture")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DurationReturn")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DurationTotal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("FacilitatedBookingAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("FareAdults")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FareChildern")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FareInfants")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("FlyFrom")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FlyTo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("HasAirportChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("HiddenCityTicketing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("KiwiId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LocalArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LocalDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LocalReturnArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LocalReturnDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NightsInDest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PnrCount")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Quality")
                        .HasColumnType("float");

                    b.Property<int>("TechnicalStops")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("ThrowAwayTicketing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UtcArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UtcDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VirtualInterlining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("KiwiId")
                        .IsUnique();

                    b.HasIndex("UtcDeparture");

                    b.HasIndex("CityCodeFrom", "CityCodeTo");

                    b.HasIndex("CityCodeFrom", "UtcDeparture");

                    b.HasIndex("FlyFrom", "FlyTo");

                    b.ToTable("Flights", (string)null);
                });

            modelBuilder.Entity("WeekendFlights.Domain.Entities.FlightsImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastCityCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("DateTimeUtc")
                        .HasDatabaseName("idx_flights_imports_datetime");

                    b.HasIndex("LastCityCode")
                        .HasDatabaseName("idx_flights_imports_last_city_code");

                    b.ToTable("flights_imports", (string)null);
                });

            modelBuilder.Entity("WeekendFlights.Domain.Entities.Airport", b =>
                {
                    b.HasOne("WeekendFlights.Domain.Entities.City", "City")
                        .WithMany("Airports")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WeekendFlights.Domain.Entities.City", b =>
                {
                    b.Navigation("Airports");
                });
#pragma warning restore 612, 618
        }
    }
}
